extract_days: 10
utility:
  api_url: https://novec.smarthub.coop
  username: johndoe@gmail.com
  password: novec_password
  account: 1234567001
  service_location: 123456
influxdb:
  host: https://localhost:8428
  auth_token: johndoe:influx_password
  database: db_name
  insecure: false
