extract_days: 10
smarthub:
  api_url: https://novec.smarthub.coop
  username: johndoe@gmail.com
  password: smarthub_password
  account: 1234567001
  service_location: 123456
  timezone: America/New_York
