name: Build electric-usage-downloader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v -o electric-usage-downloader main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: electric-usage-downloader
        path: electric-usage-downloader
